[endpoints.delete]
path = "delete"
methods = ["DELETE"]
action.fixed.status = 200

[endpoints.get]
path = "get"
methods = ["GET"]
action.fixed.status = 200

[endpoints.head]
path = "head"
methods = ["HEAD"]
action.fixed.status = 200

[endpoints.patch]
path = "patch"
methods = ["PATCH"]
action.fixed.status = 200

[endpoints.post]
path = "post"
methods = ["POST"]
action.fixed.status = 200

[endpoints.put]
path = "put"
methods = ["PUT"]
action.fixed.status = 200

[endpoints.100]
path = "100"
action.fixed.status = 100
action.fixed.text = "100 Continue"

[endpoints.200]
path = "200"
[endpoints.200.action]
action = "fixed"
[endpoints.200.action.fixed]
status = 200
text = "200 OK"
json = '{"code":200,"description":"OK"}'

[endpoints.201]
path = "201"
action.action = "fixed"
action.fixed.status = 201
action.fixed.text = "201 Created"
action.fixed.json = '{"code":201,"description":"Created"}'

[endpoints.202]
path = "202"
action.action = "fixed"
action.fixed.status = 202
action.fixed.text = "202 Accepted"
action.fixed.json = '{"code":202,"description":"Accepted"}'

[endpoints.404]
path = "404"
action.action = "fixed"
action.fixed.status = 404
action.fixed.text = "404 Not Found"
action.fixed.json = '{"code":404,"description":"Not Found"}'

[endpoints.418]
path = "418"
action.action = "fixed"
action.fixed.status = 418
action.fixed.text = "418 I'm a teapot"
action.fixed.json = "{\"code\":418,\"description\":\"I'm a teapot\"}"

[endpoints.500]
path = "500"
action.action = "fixed"
action.fixed.status = 500
action.fixed.text = "500 Internal Server Error"
action.fixed.json = "{\"code\":500,\"description\":\"Internal Server Error\"}"
[[endpoints.500.middleware]]
middleware = "sleep"
[endpoints.500.middleware.sleep]
distribution = "uniform"
[endpoints.500.middleware.sleep.uniform]
a = 50
b = 150

[endpoints.hello]
path = "hello"
action.action = "fixed"
action.fixed.status = 200
action.fixed.text = "Hello, world!"
action.fixed.json = '{"message":"Hello, world!"}'
[[endpoints.hello.middleware]]
middleware = "sleep"
[endpoints.hello.middleware.sleep]
distribution = "normal"
[endpoints.hello.middleware.sleep.uniform]
a = 500
b = 2500
[endpoints.hello.middleware.sleep.normal]
mean = 1000
stddev = 250
[[endpoints.hello.middleware]]
middleware = "fail"
[endpoints.hello.middleware.fail]
distribution = "bernoulli"
[endpoints.hello.middleware.fail.bernoulli]
p = 0.5

[endpoints.joke]
path = "joke"
action.action = "request"
action.request.method = "GET"
action.request.url = "https://icanhazdadjoke.com"
action.request.headers = [ "Accept: application/json" ]
