[endpoints.delete]
path = "delete"
methods = ["DELETE"]
status = 200

[endpoints.get]
path = "get"
methods = ["GET"]
status = 200

[endpoints.head]
path = "head"
methods = ["HEAD"]
status = 200

[endpoints.patch]
path = "patch"
methods = ["PATCH"]
status = 200

[endpoints.post]
path = "post"
methods = ["POST"]
status = 200

[endpoints.put]
path = "put"
methods = ["PUT"]
status = 200

[endpoints.100]
path = "100"
status = 100
response.text = "100 Continue"

[endpoints.200]
path = "200"
status = 200
response.text = "200 OK"
response.json = '{"code":200,"description":"OK"}'

[endpoints.201]
path = "201"
status = 201
response.text = "201 Created"
response.json = '{"code":201,"description":"Created"}'

[endpoints.202]
path = "202"
status = 202
response.text = "202 Accepted"
response.json = '{"code":202,"description":"Accepted"}'

[endpoints.404]
path = "404"
status = 404
response.text = "404 Not Found"
response.json = '{"code":404,"description":"Not Found"}'

[endpoints.418]
path = "418"
status = 418
response.text = "418 I'm a teapot"
response.json = "{\"code\":418,\"description\":\"I'm a teapot\"}"

[endpoints.500]
path = "500"
status = 500
response.text = "500 Internal Server Error"
response.json = "{\"code\":500,\"description\":\"Internal Server Error\"}"

[endpoints.hello]
path = "hello"
status = 200
response.text = "Hello, world!"
response.json = '{"message":"Hello, world!"}'
